apiVersion: v1
kind: Pod
metadata:
  generateName: wordpress-mysql-3273438642-
  labels:
    app: wordpress
    tier: mysql
  name: wordpress-mysql-3273438642-5kx47
  namespace: test
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: "1234567"
    image: reg.local:5000/common/mysql:5.7
    imagePullPolicy: IfNotPresent
    name: mysql
    ports:
    - containerPort: 3306
      hostPort: 3306
      name: mysql
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-persistent-storage
  dnsPolicy: ClusterFirst
  hostNetwork: true
  restartPolicy: Always
  securityContext: {}
  volumes:
  - hostPath:
      path: /data/mysql
    name: mysql-persistent-storage
